project:
  type: website
  output-dir: docs

website:
  title: "Übung Statistik II"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Über


format:
  html:
    lang: de
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

